### PR TITLE
Bump jmh version to 1.36

### PR DESCRIPTION
**Pull request by limansky**

### CODE REVIEW

**Review by guizmaii — APPROVED** [review]

**Comment by plokhotnyuk** [comment]
Currently the latest version is 1.36 with a lot of improvements and bug fixes: https://github.com/openjdk/jmh/compare/1.35...1.36

**Comment by limansky** [comment]
> Currently the latest version is 1.36 with a lot of improvements and bug fixes: [openjdk/jmh@1.35...1.36](https://github.com/openjdk/jmh/compare/1.35...1.36)

Fixed.

**Comment by guizmaii** [comment]
@johanandren Can you maybe merge this PR and release a new version, please? 🙏

**Comment by limansky** [comment]
Should I also update readme in this PR?

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
Looks like a bad day to interact with sonatype it seems, will try again later.

**Comment by plokhotnyuk** [comment]
Yep, oss.sonatype.org is extremely unstable these days: https://status.maven.org/

**Comment by johanandren** [comment]
0.4.4 with this bump of jmh available from maven central now

**Comment by guizmaii** [comment]
Thanks @johanandren 🙏

**Pull request merged**
